# Generated by Django 2.1.7 on 2019-03-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altName', models.CharField(max_length=30)),
                ('idNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('idNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('parent', models.IntegerField()),
                ('rank', models.CharField(max_length=30)),
                ('sciName', models.CharField(max_length=30)),
                ('comName', models.CharField(max_length=30)),
                ('genComName', models.CharField(max_length=30)),
                ('gcID', models.IntegerField()),
                ('mgcID', models.IntegerField()),
            ],
        ),
    ]
