# Generated by Django 2.1.7 on 2019-03-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='comName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='gcID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='genComName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='mgcID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='parent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='rank',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='sciName',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
